### ISSUE TITLE
Error when onnect server from local windows to ubuntu server

### ISSUE THREAD

**Issue by uarefans** [rupadana/code-deploy#1]
Connection failed status 'Terminated' when connect to server

I try to debug, with same command line ssh -i -v folder/file in storage files user@host can connect to server if using terminal windows.

i try to using spatie/ssh documentation ssh::create(user, host) from laravel but failed too without error output only " " showing

Maybe problem is from 
Let me know, what local you are using, unix or windows? 

thank you

**Comment by rupadana** [comment]
Im using MacOS, i didn't test it on windows before. 
maybe u can use WSL on your development environment

**Comment by teshanna969** [comment]
Yes, testing on ubuntu 20.04 (not wsl) working perfectly , maybe i'll try later on windows once again maybe issue with firewall or other things and let you know if working, 

And can you please update docs how to connect with github account, i try myself and success but maybe confusing for other people

1. make sure your github have name not username
2. went you create app key, make sure giving permission to read your email, because i track in socialment plugins, they need name and email, github itself default is none
3. add to .env for github_id & github_secret and github_callback
4. check to provider

Thank you

**Comment by uarefans** [comment]
Yes, testing on ubuntu 20.04 (not wsl) working perfectly , maybe i'll try later on windows once again maybe issue with firewall or other things and let you know if working,

And can you please update docs how to connect with github account, i try myself and success but maybe confusing for other people

1. make sure your github have name not only username
2. went you create github secret key, make sure giving permission to read your email, because i track in socialment plugins, they need name and email, github itself default is none
3. add to .env for github_id & github_secret and github_callback
4. check your provider same with your .env

Thank you

**Comment by rupadana** [comment]
> Yes, testing on ubuntu 20.04 (not wsl) working perfectly , maybe i'll try later on windows once again maybe issue with firewall or other things and let you know if working,
> 
> And can you please update docs how to connect with github account, i try myself and success but maybe confusing for other people
> 
> 1. make sure your github have name not only username
> 2. went you create github secret key, make sure giving permission to read your email, because i track in socialment plugins, they need name and email, github itself default is none
> 3. add to .env for github_id & github_secret and github_callback
> 4. check your provider same with your .env
> 
> Thank you

Thank you bro, ill update it ASAP.
